name: create runner # workflow name
on: workflow_dispatch
jobs: 
  create-runner:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: list files
        run: ls -la

      - name: trigger PROD deploy
        if: github.ref == 'refs/heads/main'
        run: echo "deploy to PROD"

      - name: trigger DEV deploy
        if: github.ref == 'refs/heads/feature-*'
        run: echo "deploy to DEV"